PickleSong/config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :playlists
  resources :songs
  resources :results
  root "welcome#index"
  post '/' => 'welcome#index'

end

PickleSong/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :song_playlists
  has_many :songs, through: :song_playlists
  validates :name, presence: true
end

PickleSong/app/models/song.rb
class Song < ActiveRecord::Base
  has_many :song_playlists
  has_many :playlists, through: :song_playlists
end

PickleSong/app/models/song_playlist.rb
class SongPlaylist < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

PickleSong/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

PickleSong/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

PickleSong/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create!(playlist_params)
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
  end

  def edit
  end

  def update
  end

  def destroy
    @playlist = Playlist.destroy(params[:id])
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name, :id)
  end
end

PickleSong/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def new
  end

  def create
    @query = SongPicklr::Search.new(params[:q])
    @results = @query.query_items
    @main = @results.first
    @alternatives = @results
    @playlists = Playlist.all
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js
    end
  end
end

PickleSong/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def create
    @song = Song.create(song_params)
    @active_playlist = Playlist.find(params[:playlist].to_i)
    @active_playlist.songs << @song
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js
    end
  end

  def new
  end

  def destroy
  end

  private
  def song_params
    params.require(:song).permit(:title, :video_id, :url, :thumbnail, :embed_url)
  end
end

PickleSong/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @playlists = Playlist.all
    @query = SongPicklr::Search.new("push it")
    @results = @query.query_items
    @main = @results.first
  end
end

PickleSong/app/helpers/application_helper.rb
module ApplicationHelper
end

PickleSong/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

PickleSong/app/helpers/results_helper.rb
module ResultsHelper
end

PickleSong/app/helpers/songs_helper.rb
module SongsHelper
end

PickleSong/app/helpers/videos_helper.rb
module VideosHelper
end

PickleSong/app/helpers/welcome_helper.rb
module WelcomeHelper
end

PickleSong/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>PickleSong</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    </head>
    <body>
        <div id="container">
            <div class="outter">
                <!-- BEGIN NAVBAR -->
                <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <%= link_to '/', :class=>"navbar-brand" do %>
                                <%= image_tag("pickles-128.png", :alt => "logo", :title => "Home", :class=>"images", :id=>"logo", :size=>"28") %>PicklSong
                            <% end %>
                            <%# link_to image_tag("pickles-128.png", :alt => "logo", :title => "Home", :class=>"images", :id=>"logo", :size=>"28") + "PicklSong", "/", :class=>"navbar-brand" %>
                            <%=render "results/form"%>
                        </div><!--navbar-header-->

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <% if user_signed_in? %>
                                    <li><%= link_to 'EDIT PROFILE', edit_user_registration_path %></li>
                                    <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                                    <li class="dropdown">
                                        <%=render "playlists/playlist_dropdown"%>
                                    </li><!--dropdown-->
                                <% else %>
                                    <li><%= link_to "SIGN UP", new_user_registration_path %></li>
                                    <li><%= link_to "LOGIN", new_user_session_path %></li>
                                <% end %>
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.container-fluid -->
                </nav>
                <!-- END NAVBAR -->
            </div><!--outter-->

            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, id: "flash_#{name}" %>
            <% end %>

            <%= yield %>
        </div><!--container-->
    </body>
</html>

PickleSong/app/views/playlists/_form.html.erb
  <%=form_for @playlist, remote: true do |f|%>
    <%= f.text_field :name%>
    <%= f.submit :id => "playlist_submit"%>
  <%end%>

PickleSong/app/views/playlists/_playlist.html.erb
<div id="playlist_panel">

  <span class="dropdown polls-subtitle">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Playlists<b class="caret"></b></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to "New Playlist", new_playlist_path, id: "new_link", remote: true %></li>
        <%@playlists.each_with_index do |playlist, i|%>
          <li id= "<%=playlist.id%>" class="playlist" data-songs="<%=playlist.songs.to_json%>" data-playlistid="<%=playlist.id%>" data-name="<%=playlist.name%>"> <%=playlist.name%></li>
        <%end%>
    </ul>
  </span>

  <div id="playlist_songs">
  </div>

</div>

PickleSong/app/views/playlists/_playlist_dropdown.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown">PLAYLISTS<b class="caret"></b></a>
<ul class="dropdown-menu" role="menu">
    <li><%= link_to "New Playlist", new_playlist_path, id: "new_link", remote: true %></li>
    <%@playlists.each do |playlist|%>
        <li><a class="playlist" data-songs="<%=playlist.songs.to_json%>" id="<%=playlist.id%>" data-name="<%=playlist.name%>" data-playlistid="<%=playlist.id%>"><%=playlist.name%>
       </a></li>
    <%end%>
</ul>

PickleSong/app/views/playlists/_playlist_index.html.erb
<div id="playlist_panel">
    <div id="playlist_songs">
    </div>
</div>

PickleSong/app/views/playlists/_query_form.html.erb
<div class="widget">
    <%= form_tag do %>
        <form role="form">
            <div class="form-group"
                <%= label_tag(:q, "Pickl a song to sing:") %>
                <%= text_field_tag(:q) %>
            </div>
            <%= submit_tag("Search") %>
        </form>
    <% end %>
</div>

PickleSong/app/views/playlists/create.js.erb
$('.new_playlist').remove();
$('#new_link').show();
$('.dropdown-menu').append("<li><a id=" + '<%= j Playlist.last.id.to_s%>' + " class='playlist' data-songs=" + '<%=j Playlist.last.songs.to_json%>' + " data-playlistid=" + '<%= j Playlist.last.id.to_s%>' + " data-name='" + '<%= j Playlist.last.name %>' + "'>" + '<%= j Playlist.last.name %>' + "</a></li>");
$('.playlist').click(function() {
    var id = $(this).data('playlistid');
    var name = $(this).data('name')
    $('#playlist_songs').empty();
    $('#playlist_songs').append("<h4 class='active-playlist' data-id=" + id + ">" + name + "</h4>")
    $('#playlist_songs').append("<a class='delete-button'><i class='fa fa-minus-circle'></i></a>");
    $('.delete-button').click(function() {
        var playlist = $('.active-playlist').data('id');
        $.ajax({
            url: "/playlists/" + id,
            type: "DELETE"
        });
    });
});

PickleSong/app/views/playlists/destroy.js.erb
$('.active-playlist').remove();
$('.delete-button').remove();
$('.song').remove();
$('#<%= @playlist.id %>').remove();

PickleSong/app/views/playlists/edit.html.erb
<h1>Playlists#edit</h1>
<p>Find me in app/views/playlists/edit.html.erb</p>

PickleSong/app/views/playlists/index.html.erb
<div class="section-outter">
    <div class="section-wrapper">

        <div class="col-md-9">
         <% if @results %>
            <h1><%= @first_result.title %></h1>
            <iframe width="853" height="480" src="//<%= @first_result.embed_url %>" frameborder="0" allowfullscreen></iframe>

            <div id="results">
                <div class="section-inner">
                    <ul id="og-grid" class="og-grid">
                        <% @alternatives.each do |result| %>
                        <li>
                            <div class="og-overlay"></div>
                            <p class="og-title truncate"><%= result.title %></p>
                            <iframe width="372" height="210" src="//<%= result.embed_url %>" frameborder="0" allowfullscreen></iframe>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div><!--results-->
            <% end %>
         </div><!--col-md-9-->
        <div class="col-md-3">
            <%= render "query_form" %>
        </div>
    </div><!--section-wrapper-->
  <%= render "playlist"%>
</div><!--section-outer-->

PickleSong/app/views/playlists/new.html.erb
<%= render "form" %>

PickleSong/app/views/playlists/new.js.erb
$('#new_link').hide().after('<%= j render "form" %>');

PickleSong/app/views/playlists/show.html.erb
show.html.erb

PickleSong/app/views/results/_form.html.erb
<%= form_tag results_path, id: "search", remote: true do %>
    <!-- <form class="navbar-form navbar-left form-inline"> -->
    <div class="input-group">
        <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Pickl A Song", autofocus: "true") %>
        <span class="input-group-btn">
            <%= button_tag(type: "submit", class: "btn btn-default") do %>
                <i class="fa fa-search"></i>
            <% end %>
        </span><!--input-group-btn-->
    </div><!--input-group-->
</form>
<% end %>

PickleSong/app/views/results/_vidmain.html.erb
<!--Main video-->
<h3 id="active-song-title"><%= @main.title %></h3>
<div class="vid-container">
    <iframe id="vid_frame" width="853" height="480" src="//<%= @main.embed_url %>" frameborder="0" allowfullscreen>
    </iframe>
</div>

PickleSong/app/views/results/_vidresults.html.erb
<!--Results List-->
<div class="vid-list-container">
    <div class="vid-list">
        <% @alternatives.each_with_index do |result, index| %>
            <div class="vid-item", data-attributes="<%= result.attributes.to_json %>">
                <div class="thumb">
                    <img src="<%= result.thumbnail %>">
                </div>
                <div class="desc truncate line-clamp">
                    <%= result.title %>
                </div>
            </div>
            <% end %>
    </div><!--vid-list-->
</div><!--vid-list-container-->
<div class="arrows">
    <div class="arrow-left"><i class="fa fa-chevron-left fa-lg"></i></div>
    <div class="arrow-right"><i class="fa fa-chevron-right fa-lg"></i></div>
</div>

PickleSong/app/views/results/create.html.erb
<h1>Results#create</h1>
<p>Find me in app/views/results/create.html.erb</p>

PickleSong/app/views/results/create.js.erb
if ($('.main-video').children().length === 0){
    $('.main-video').html("<%= j(render("results/vidmain")) %>");
}

$('.search-results').html("<%= j(render("results/vidresults")) %>");

$(document).ready(function() {
    $('.vid-item').click(function() {
        console.log('clicked');
        var vidAttributes = $(this).data('attributes');
        var activePlaylist = $('.active-playlist').data('id');
        $.ajax({
            type: "POST",
            url: "/songs",
            data: {song: vidAttributes, playlist: activePlaylist},
            dataType: 'script',
            success: console.log("It worked!", vidAttributes, activePlaylist)
        });
    });
});

$(document).ready(function() {
    $(".arrow-right").bind("click", function(event) {
        event.preventDefault();
        $(".vid-list-container").stop().animate({
            scrollLeft: "+=336"
        }, 750);
    });
    $(".arrow-left").bind("click", function(event) {
        event.preventDefault();
        $(".vid-list-container").stop().animate({
            scrollLeft: "-=336"
        }, 750);
    });
});

PickleSong/app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

PickleSong/app/views/songs/create.js.erb
$('#playlist_songs').append("<div class='clearfix'><div class='song' data-embed-url='<%= j Song.last.embed_url %>' data-title='<%= j Song.last.title %>'><span id='pl-song-thumb'><img src='<%=j Song.last.thumbnail%>'></span><h4 id='pl-song-title' class='truncate'><%= j Song.last.title %></h4></div></div>");
$('.song').click(function() {
    console.log("clicked playlist's song");
    var vidTitle = $(this).data('title');
    console.log(vidTitle);
    $('#active-song-title').text(vidTitle);
    var embedUrl = $(this).data('embed-url');
    document.getElementById('vid_frame').src = "//" + embedUrl;
});

PickleSong/app/views/songs/destroy.html.erb
<h1>Songs#destroy</h1>
<p>Find me in app/views/songs/destroy.html.erb</p>

PickleSong/app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

PickleSong/app/views/welcome/_playlist_panel.html.erb
<div id="playlist_panel">

  <span class="dropdown polls-subtitle">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Playlists<b class="caret"></b></a>
    <ul class="dropdown-menu" role="menu">
        <li class="new_playlist">New playlist</li>
        <%@playlists.each_with_index do |playlist, i|%>
          <li class="playlist" data-songs="<%=playlist.songs.to_json%>" data-playlistid="<%=playlist.id%>" data-name="<%=playlist.name%>"> <%=playlist.name%></li>
        <%end%>
    </ul>
  </span>

  <div id="playlist_songs">
  </div>

</div>

<div class="form">
  <%=form_tag controller: "welcome", action: "create", method: "post" do%>
    <%= text_field_tag "playlist[name]"%>
    <%= submit_tag%>
  <%end%>
</div>

PickleSong/app/views/welcome/index.html.erb
<div class="section-outer">
    <div class="section-wrapper">
        <div class="col-md-9">
            <div class="main-video">
                <%= render "results/vidmain"%>
            </div>
            <div class="search-results"></div>
        </div><!--col-md-9-->
        <div class="col-md-3">
            <%= render "playlists/playlist_index" %>
        </div><!--col-md-3-->
    </div><!--section-wrapper-->
</div><!--section-outer-->